/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bird(props) {
  const { nodes, materials } = useGLTF('./bird_material.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bird002.geometry} material={materials.bird} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wings001.geometry}
        material={materials['bird.001']}
        position={[0.349, -0.072, 0.005]}
        rotation={[-0.097, 0.092, 0.583]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.top001.geometry}
        material={materials['Material.004']}
        position={[-0.02, 0.243, 0.158]}
        rotation={[1.37, 0.205, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyes001.geometry}
        material={materials.uruuru_eye}
        // you can adjust material like this. syntax is material-*
        material-roughness={0.1}
        position={[0.102, -0.023, 0.241]}
        rotation={[-0.26, 0.33, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nose001.geometry}
        material={materials.bird_beak}
        position={[0, -0.049, 0.285]}
        rotation={[1.392, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./bird_material.glb')
